# Feel free to delete these and replace with your workflow

name: Rubocop

on: [push]

jobs:
  
  build:
    name: Rubocop
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Rubocop Linter
      uses: andrewmcodes/rubocop-linter-action@v3.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
